import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { prompt } = await request.json();

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    // Call Bedrock via AWS SDK (server-side only)
    const response = await fetch(
      `https://bedrock-runtime.us-east-1.amazonaws.com/model/us.anthropic.claude-sonnet-4-6/invoke`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          anthropic_version: "bedrock-2023-05-31",
          max_tokens: 4096,
          messages: [
            {
              role: "user",
              content: `Generate a React component using Tailwind CSS and shadcn/ui for: ${prompt}. Output ONLY the JSX code, no explanations.`,
            },
          ],
        }),
      }
    );

    if (!response.ok) {
      // Fallback: return a placeholder component
      return NextResponse.json({
        code: `// Generated component for: ${prompt}
export default function GeneratedComponent() {
  return (
    <div className="p-8 space-y-4">
      <h1 className="text-2xl font-bold">${prompt}</h1>
      <p className="text-muted-foreground">Component generated by Nova Super Agent</p>
      <button className="bg-accent text-accent-foreground px-4 py-2 rounded-md hover:bg-accent/90">
        Click Me
      </button>
    </div>
  );
}`,
      });
    }

    const data = await response.json();
    const code = data.content?.[0]?.text || "// No code generated";

    return NextResponse.json({ code });
  } catch (err) {
    return NextResponse.json(
      { error: "Generation failed", details: String(err) },
      { status: 500 }
    );
  }
}
